Algoritmo "numeroMenorQueTrês"
// Disciplina  :  [Linguagem e Lógica de Programação com visualG]
// Professor   : Jailson
// Descrição   : o algoritimo solicita um valor e so vai informar se ele for
// menor que 3
// Data atual  : 11/04/2025
Var
// Seção de Declarações das variáveis

num1:real

Inicio

escreval("Digite um número: ")
leia(num1)

se (num1 <= 3) entao
escreval("O numero digitado é: ",num1)
fimse




Fimalgoritmo