algoritmo "valoresTrocados"
// Função : o algoritmo captura dois valores e exibe o valores trocados.
// Autor :  Alexandre Ferreira
// Data : 02/04/2025
// Seção de Declarações 
var
valorA:inteiro
ValorB:inteiro


inicio
// Seção de Comandos 
escreva("Digite o valor A: ")
leia (valorA)
escreval("")
escreva("Digite o valor B: ")
leia (valorB)
escreval("")


escreval("O valor A é: ", valorB)
escreval("O valor B é: ", valorA)






fimalgoritmo
