algoritmo "celciusEmFahrenheit"
// Função : o algoritmo captura a temperatura em celcius e converte em fahrenheit.
// Autor :  Alexandre Ferreira
// Data : 02/04/2025
// Seção de Declarações 
var
celcius:real
faren:real
calculo:real

inicio
// Seção de Comandos 
escreva("Digite a temperatura em graus Celcius: ")
leia (celcius)
escreval("")

calculo <- (9 * celcius + 160) / 5

escreva("A temperatura digitada em Fahrenheit é: ", calculo, " ºF")


fimalgoritmo
