algoritmo "fahrenheitEmCelcius"
// Função : o algoritmo captura a temperatura em fahrenheit e converte para celcius.
// Autor :  Alexandre Ferreira
// Data : 02/04/2025
// Seção de Declarações 
var
faren:real
calculo:real

inicio
// Seção de Comandos 
escreva("Digite a temperatura em graus Fahrenheit: ")
leia (faren)
escreval("")

calculo <- (faren - 32) * (5/9)

escreva("A temperatura digitada em Celcius é: ", calculo, " ºC")


fimalgoritmo
